### PR TITLE
Fix typo on README.md

### PR DESCRIPTION
**Pull request by milesmatthias**

### CODE REVIEW

**Comment by chrislovecnm** [comment]
ok to test

**Comment by chrislovecnm** [comment]
please test this

**Comment by chrislovecnm** [comment]
@milesmatthias can you do an amend and fix the user on this commit please

**Comment by chrislovecnm** [comment]
test this please

**Comment by chrislovecnm** [comment]
test this please

**Comment by milesmatthias** [comment]
@chrislovecnm user fixed

**Comment by chrislovecnm** [comment]
/lgtm

THANKS!!

**Comment by milesmatthias** [comment]
@chrislovecnm nope, don't have permissions :( Do I need to be added to https://github.com/orgs/GoogleCloudPlatform/teams/gke-helmsman-contributors?

**Pull request merged**
