### PR TITLE
use scripted Jenkinsfile to solve version bump issue

### PR DESCRIPTION
**Pull request by pydevops**

### CODE REVIEW

**Comment by chrislovecnm** [comment]
@cxhercules you know a lot more about the validate scripts now.  Any comments?

**Comment by pydevops** [comment]
@cxhercules @chrislovecnm any idea why we removed the external service IP and service itself check. I have enhanced the validate.sh based on the last commit of the MASTER branch, it was failing earlier.

**Comment by cxhercules** [comment]
Taking a look.

**Comment by pydevops** [comment]
> So I think the check looks fine, it really depends on how the service is exposed and in this case a load balancer is used which I think should behave better. Once you get the initial 200 I believe you should be good, on one of the projects I had to wait for all backends to be healthy, I don't think you will need that here. Also noticed that there is 1 replica so would not need to balance between pod sets.

So we don't need to check IP and service (IP+port) anymore? If that is the case, I can rebase to upstream/master and revert my change on validate.sh.

**Comment by cxhercules** [comment]
> > So I think the check looks fine, it really depends on how the service is exposed and in this case a load balancer is used which I think should behave better. Once you get the initial 200 I believe you should be good, on one of the projects I had to wait for all backends to be healthy, I don't think you will need that here. Also noticed that there is 1 replica so would not need to balance between pod sets.
> 
> So we don't need to check IP and service (IP+port) anymore? If that is the case, I can rebase to upstream/master and revert my change on validate.sh.

We would check the load balancer IP and port, which is the exposed service. If that is what you mean then yes we need to check it.

**Pull request merged**
